// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: map_transactions.sql

package store

import (
	"context"
)

const transMapsRmCategories = `-- name: TransMapsRmCategories :exec
WITH deleted AS (
    DELETE FROM mapped_transactions
    WHERE mapping_id = $1
    RETURNING trans_id
) UPDATE transactions
SET resolved_category = NULL
FROM deleted
WHERE id = deleted.trans_id
`

func (q *DBStore) TransMapsRmCategories(ctx context.Context, mappingID string) error {
	_, err := q.db.Exec(ctx, transMapsRmCategories, mappingID)
	return err
}

const transMapsRmNames = `-- name: TransMapsRmNames :exec
WITH deleted AS (
    DELETE FROM mapped_transactions
    WHERE mapping_id = $1
    RETURNING trans_id
) UPDATE transactions
SET resolved_name = NULL
FROM deleted
WHERE id = deleted.trans_id
`

func (q *DBStore) TransMapsRmNames(ctx context.Context, mappingID string) error {
	_, err := q.db.Exec(ctx, transMapsRmNames, mappingID)
	return err
}
